# Generated by Django 2.2.4 on 2019-08-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190803_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
