# Generated by Django 2.2.4 on 2019-08-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190803_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Timeout')),
                ('binNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='AFC',
        ),
    ]
