# Generated by Django 2.2.4 on 2019-08-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190803_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=200)),
                ('correctNum', models.IntegerField(default=0)),
                ('wrongNum', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='reviewcard',
            name='correctNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewcard',
            name='wrongNum',
            field=models.IntegerField(default=0),
        ),
    ]
